parameter_defaults:
  ControlPlaneDefaultRoute: "172.16.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['8.8.8.8','8.8.4.4']
  EC2MetadataIp: "172.16.0.1"

  ExternalAllocationPools: [{'start': '10.9.88.200', 'end': '10.9.88.220'}]
  ExternalNetCidr: "10.9.88.0/24"
  #ExternalNetworkVlanID: 10
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.9.88.254"

  InternalApiNetCidr: 10.12.81.0/24
  StorageNetCidr: 10.12.82.0/24
  StorageMgmtNetCidr: 10.12.83.0/24
  TenantNetCidr: 10.12.84.0/24
  InternalApiNetworkVlanID: 231
  StorageNetworkVlanID: 232
  StorageMgmtNetworkVlanID: 233
  TenantNetworkVlanID: 234
  InternalApiAllocationPools: [{'start': '10.12.81.20', 'end': '10.12.81.200'}]
  StorageAllocationPools: [{'start': '10.12.82.20', 'end': '10.12.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.12.83.20', 'end': '10.12.83.200'}]
  TenantAllocationPools: [{'start': '10.12.84.20', 'end': '10.12.84.200'}]

  LocalProvisioningNicName: p5p1
