parameter_defaults:
  ComputeSriovParameters:
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=32 iommu=pt intel_iommu=on
    TunedProfileName: "cpu-partitioning"
    IsolCpusList: "4,48,5,49,6,50,7,51"
    NovaVcpuPinSet: ['4,48,5,49,6,50,7,51']
    NovaReservedHostMemory: 4096
